Pentium basic
dbakti7/GameMaster pull request #6
Opened 2017-08-02 07:33 UTC by cacad101

Basic function
- Login
- Signup
- Logout
- View Home

2017-08-02 15:03 UTC, dbakti7 commented on storage/db.go
> +	"github.com/cacad-ntu/GameMaster/models"
2 tabs? @cacad101

2017-08-02 15:05 UTC, dbakti7 commented on storage/user.go
> +	"github.com/cacad-ntu/GameMaster/models"
Thanks for fixing this, too lazy at that time. lol

2017-08-02 15:52 UTC, dbakti7 commented on resources/styles.css
> +  padding: 30px;
Fix indent.

2017-08-02 16:02 UTC, dbakti7 requested changes

2017-08-02 16:02 UTC, dbakti7 commented on handler/user.go
> +	secretKey = "diangoblok"
change this, else your PR will be rejected. @cacad101

2017-08-03 03:31 UTC, cacad101 commented on storage/db.go
> +	"github.com/cacad-ntu/GameMaster/models"
Not sure about this on local are using 4 space indent

2017-08-03 03:33 UTC, cacad101 commented on resources/styles.css
> +  padding: 30px;
Fixed

2017-08-03 03:35 UTC, cacad101 commented on handler/user.go
> +	secretKey = "diangoblok"
Changed

2017-08-03 17:08 UTC, dbakti7 commented on handler/user.go
>  	issuer    = "cacad-ntu"
Not-approved! @cacad101 
I suggest "pentium-inside"

2017-08-03 17:09 UTC, dbakti7 commented on storage/db.go
> +	"github.com/cacad-ntu/GameMaster/models"
I will try fixing it and standardize our setting after this PR merged.

2017-08-03 17:13 UTC, dbakti7 reviewed
Logic wise seems fine. Change the secretkey and merge it! @cacad101

2017-08-03 17:14 UTC, dbakti7 commented on html/home.html
> +    <title></title>
Small stuff, can be TODO: add title later. @cacad101

2017-08-03 17:14 UTC, dbakti7 commented on html/login.html
> +    <title></title>
Same here, title. @cacad101

2017-08-08 14:13 UTC, cacad101 commented on html/home.html
> +    <title></title>
Okay

2017-08-08 14:13 UTC, cacad101 commented on html/login.html
> +    <title></title>
Okay

2017-08-08 14:14 UTC, cacad101 commented on storage/db.go
> +	"github.com/cacad-ntu/GameMaster/models"
Okay

2017-08-08 14:16 UTC, merged